const EMPLOYEES = {
	LOAD: "EMPLOYEES_START",
	LOAD_SUCCESS: "EMPLOYEES_SUCCESS",
	LOAD_FAILED: "EMPLOYEES_FAILED",
};

const CREATE_EMPLOYEES = {
	CREATE: "CREATE_EMPLOYEES_START",
	CREATE_SUCCESS: "CREATE_EMPLOYEES_SUCCESS",
	CREATE_FAILED: "CREATE_EMPLOYEES_FAILED",
};

const UPDATE_EMPLOYEES = {
	UPDATE_EMPLOYEES_START: "UPDATE_EMPLOYEES_START",
	UPDATE_EMPLOYEES_SUCCESS: "UPDATE_EMPLOYEES_SUCCESS",
	UPDATE_EMPLOYEES_FAILED: "UPDATE_EMPLOYEES_FAILED",
};

export default {
	EMPLOYEES,
	CREATE_EMPLOYEES,
	UPDATE_EMPLOYEES,
};
